version: "3.9"
services:
  flask:
    build: src/
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - mariadb
    links: 
        - mariadb
  mariadb:
    image: mariadb:10.3.32-focal
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "train"
