version: "3.9"  # optional since v1.27.0
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - logvolume01:/var/log
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
volumes:
  logvolume01: {}
